version: '3.8'

services:
  db:
    image: postgres:15.3
    restart: unless-stopped
    environment:
      - POSTGRES_DB=wonders
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=D1q9f0C2&PEW
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    entrypoint: /etc/app/wonders -m
    environment:
      - ROCKET_CONFIG=/etc/app/rocket.toml
      - ROCKET_DB=postgres://root:D1q9f0C2&PEW@db:5432/wonders
      - ROCKET_PORT=8000
      - ROCKET_CACHE=/etc/app/cache
      - ROCKET_NASA_API_KEY=XXXX-XXXX-XXXX-XXXX
      - ROCKET_API_URL=https://api.nasa.gov/planetary/apod
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - app:/etc/app/cache

  daemon:
    build: .
    restart: unless-stopped
    entrypoint: /etc/app/wonders -d
    environment:
      - ROCKET_CONFIG=/etc/app/rocket.toml
      - ROCKET_DB=postgres://root:D1q9f0C2&PEW@db:5432/wonders
      - ROCKET_PORT=8000
      - ROCKET_CACHE=/etc/app/cache
      - ROCKET_NASA_API_KEY=XXXX-XXXX-XXXX-XXXX
      - ROCKET_API_URL=https://api.nasa.gov/planetary/apod
    depends_on:
      - db
    volumes:
      - daemon:/etc/app/cache

volumes:
  db:
    driver: local
  app:
    driver: local
  daemon:
    driver: local
